### ISSUE TITLE
Is it intended that user additions with missing required fields are added to the db

### ISSUE THREAD

**Issue by sklvarjo** [uh-cs-iotlab/node-iothub#11]
If I post a new user with missing required fields, it seems that it is added to the db and if I gather it is intended that I use put to add the missing fields. Is this intended way or should the post with missing required fields be checked before addition to db?

**Comment by Nautigsam** [comment]
What are these "required fields"? If you try to post a user without email or password, which are the only required fields, then you get a 422 response and the user is not created in db.

**Comment by sklvarjo** [comment]
I just tried to post a user with a missing password and it got the 422 response but when I added the password field and tried again it said that the id is taken. Now that I look at the contents of the db it may be that the id 1 is taken by the admin user and the post of the another user failed due to that.

**Comment by Nautigsam** [comment]
Don't specify id when you create something, the id is generated by the database and you can get it in the response if the instance is created. By the way, how did you manage to look at the content of the memory db?

**Comment by sklvarjo** [comment]
Use the API to list all the users :)

**Comment by Nautigsam** [comment]
Oh okay, then. The admin is indeed the first user that is added to the db when you launch the hub. The thing is the ids are not the same depending on whether you use memory or mongodb. For mongo, ids look like a big base64 string. We can't expect any format in particular, that's why it is better to let the dao layer to define ids.
