### ISSUE TITLE
Shall we decide on a style guide?

### ISSUE THREAD

**Issue by Nautigsam** [uh-cs-iotlab/node-iothub#12]
I looked at the code of @jphire and I saw that he indented with tabs. Personally I prefer to use 4 spaces but I know that there is not a better way than another. Though I think we should use the same conventions because it can lead to crappy commits with empty lines and it could be annoying. I propose you to discuss it here.

**Comment by jphire** [comment]
Agreed. I personally can change to 4 spaces easily, a matter of configuring editor settings
